name: GNPS_live_processes_env
channels:
  - conda-forge
  - bioconda
dependencies:
  - python==3.11
  - openms=3.0.0
  - pip
  - numpy
  - pandas
  - lxml
  - openpyxl
  - pip:
    - molmass
    - pyteomics==4.6.2
    - xmltodict
    - pyopenms==3.0.0
    - plotly
    - rdkit
    #- formula_validation==1.0.1

