name: GNPS_live_processes_env
channels:
  - conda-forge
dependencies:
  - python>=3.7
  - pip
  - numpy
  - pandas
  - lxml
  - openpyxl
  - pip:
    - molmass
    - pyteomics
    - xmltodict
    - pyopenms
    - formula_validation
